# Generated by Django 4.1 on 2024-04-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="genre", table="api_genre",),
        migrations.AlterModelTable(name="keyword", table="api_keyword",),
    ]
