# Generated by Django 4.1 on 2024-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_genre_table_alter_keyword_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre", name="tmdb_id", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="keyword", name="tmdb_id", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie", name="tmdb_id", field=models.IntegerField(null=True),
        ),
    ]
