# Generated by Django 4.1 on 2024-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_genre_tmdb_id_alter_keyword_tmdb_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, to="api.genre"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="keywords",
            field=models.ManyToManyField(blank=True, to="api.keyword"),
        ),
    ]
